target: discord_target_url
games:
  - yo1yq2dq
  - 8nd2wvd0
  - qw6jv76j
  - nj1n99dp
  - 29d3w01l
  - om1m3j62
  - xv1pj718
  - xldezxd3
  - om1mj412
  - m9doj36p
  - 946w971r
  - l3dxlpdy
  - 29d37g6l
  - ok6qj9dg
  - xldexx63
  - xv1py818
  - yd4kmk6e
  - vo6gv562
  - j1nyvy6p
  - y657jede
  - xkdkjq1m
  - jy65041e
  - n4d7pgd7
  - kyd4051e
  - j1lexz6g
